### ISSUE TITLE
AK4 constituents

### ISSUE THREAD

**Issue by sidnarayanan** [PandaPhysics/PandaProd#29]
@zdemirag pointed out that the proper method of propagating JEC on the fly to MET involves muon removal [1]. The matching has to be done at PF-level, but we don't save the constituents of the AK4 jets [2]. 

@yiiyama can we read the index of a Ref even if the collection the Ref points to isn't available? In this case, we just need to know if the muon is a constituent of the jet (i.e. check if the indices match), so I'm wondering if we can do this without needing to load the PF candidate collection.

[1] https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/JetMETCorrections/Type1MET/interface/PFJetMETcorrInputProducerT.h#L173-L184

[2] https://github.com/PandaPhysics/PandaProd/blob/master/Producer/python/panda_cfi.py#L22

**Comment by yiiyama** [comment]
Yes that's possible. `ref.idx()` returns the index even when the pointer to the collection is not set.

**Comment by sidnarayanan** [comment]
Or a simpler solution: we just save an ID bool (like loose, tight, monojet) applyJEC that checks if:

- It contains a PF muon
- It passes the criteria [1]. Right now we don't have these energy fractions for jets

This is probably the only case in which we'd want access to the PF candidates or EM energy fractions for AK4 jets, so why overburden the data format? What do you think @yiiyama @zdemirag @maierbenedikt ?

[1] https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/JetMETCorrections/Type1MET/interface/PFJetMETcorrInputProducerT.h#L167-L168

**Comment by zdemirag** [comment]
It could work for the em fraction but not for pf muon case (what you suggest) because you still apply the JEC even if you find a pf muon that overlaps. You just first subtract the energy of the muon.

**Comment by sidnarayanan** [comment]
Ah right. Poop.

**Comment by yiiyama** [comment]
I'll just add constituents to ak4 jets.

**Comment by sidnarayanan** [comment]
Are we also ok with adding cef and nef?

**Comment by yiiyama** [comment]
I see no reason not to.

**Comment by yiiyama** [comment]
PR #41 and #42.
